### ISSUE TITLE
npm install is down

### ISSUE THREAD

**Issue by geminiyellow** [cmackay/hybrid-boilerplate#1]
maybe you should remove gulp-xml-editor, it is out of date.

**Comment by cmackay** [comment]
hmm, maybe the mirror you are using is down. I just ran a clean build after clearing my cache and all the dependencies were retrieved successfully. What do you mean by out of date?

Thanks,

-Craig

**Comment by cmackay** [comment]
The gulp-xml-editor library is used to update the version in the cordova config.xml as part of the release and init gulp tasks. If you have suggestions on alternatives, please let me know and I would be happy to look into it. I am going to close this for now since I don't know of any issues with the current usage of this library. Let me know if you have any additional info. Thanks!

**Comment by geminiyellow** [comment]
@cmackay thanks for your reply, could you tell me your node version? i use 12.

**Comment by cmackay** [comment]
@geminiyellow  I am using an older version of node v0.10.36. I just tried switching to the latest but I was getting errors when npm install installs the sass-loader. 

> node-sass@1.2.3 postinstall /Users/cmackay/repos/hybrid-boilerplate/node_modules/sass-loader/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355

  Module._extensions[extension](this, filename);
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cmackay/repos/hybrid-boilerplate/node_modules/sass-loader/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by geminiyellow** [comment]
@cmackay yes, the `node-sass` version is too old. 
i have to modify `gulp-sass` and `sass-loader` 's config manually.
i do not use `gulp-xml-editor` now, but it may be the same reason,
the dependences packages.

**Comment by cmackay** [comment]
Thanks for the info. I will look into the dependency versions and see if I can get them working with the latest. Thanks!

**Comment by cmackay** [comment]
@geminiyellow I published a new release that appears to be working with the latest node version 0.12. I have updated all the dependencies using npm-check-updates -u and then cleared my npm cache, and ran npm install, then tested it out a bit, and then did a gulp release. Everything appears to be working. Let me know if it is working for you and if you have any additional comments or feedback. Thanks!
