### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by theho** [cmackay/hybrid-boilerplate#3]
I tried to install the repo,

```
npm install
```

and I am getting a lot of 'cannot find module',

eg,

```
Error: Cannot find module 'serve-static'
```

**Comment by cmackay** [comment]
I just cloned the project and ran npm install. I didn't see the issue you mention but I did notice a lint issue and there are changes to the latest HtmlWebPackPlugin that change the syntax in the entry template. I have checked in a fix for the lint issue and entry template changes. As for the issue you are seeing, you might want to delete the node_modules directory from within the project directory and also run `npm cache clean`. I also recommend you are running a recent version of npm and node. The versions I am using when testing locally are node v0.12.0 & npm 2.3.0.

**Comment by cmackay** [comment]
Let me know if updating node and npm along with clearing your cache helps.

Thanks,

-Craig
